/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

/**
 *
 * @author USER
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenuBar = new javax.swing.JMenuBar();
        masterMN = new javax.swing.JMenu();
        barangMN = new javax.swing.JMenuItem();
        userMN = new javax.swing.JMenuItem();
        transactionMN = new javax.swing.JMenu();
        penjuallanMN = new javax.swing.JMenuItem();
        MNreport = new javax.swing.JMenu();
        laporanMN = new javax.swing.JMenuItem();
        logoutMN = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        JMenuBar.setName(""); // NOI18N

        masterMN.setText("Master");

        barangMN.setText("Barang");
        barangMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMNActionPerformed(evt);
            }
        });
        masterMN.add(barangMN);

        userMN.setText("User");
        userMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMNActionPerformed(evt);
            }
        });
        masterMN.add(userMN);

        JMenuBar.add(masterMN);

        transactionMN.setText("Transaction");

        penjuallanMN.setText("Penjualan");
        penjuallanMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjuallanMNActionPerformed(evt);
            }
        });
        transactionMN.add(penjuallanMN);

        JMenuBar.add(transactionMN);

        MNreport.setText("Reports");

        laporanMN.setText("Form Laporan");
        laporanMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanMNActionPerformed(evt);
            }
        });
        MNreport.add(laporanMN);

        JMenuBar.add(MNreport);

        logoutMN.setText("Log Out");
        logoutMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMNActionPerformed(evt);
            }
        });
        JMenuBar.add(logoutMN);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMNActionPerformed
    FormBarang1 fBarang= new FormBarang1();
    fBarang.setLocationRelativeTo(null);
    fBarang.setVisible(true);
    }//GEN-LAST:event_barangMNActionPerformed

    private void userMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMNActionPerformed
     FormUser fUser= new FormUser();
     fUser.setLocationRelativeTo(null);
     fUser.setVisible(true);
    }//GEN-LAST:event_userMNActionPerformed

    private void penjuallanMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjuallanMNActionPerformed
     transaksi fTransaksi= new transaksi();
     fTransaksi.setLocationRelativeTo(null);
     fTransaksi.setVisible(true);
    }//GEN-LAST:event_penjuallanMNActionPerformed

    private void laporanMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanMNActionPerformed
     /*FormLaporan fLaporan= new FormLaporan();
     fLaporan.setLocationRelativeTo(null);
     fLaporan.setVisible(true);*/
    }//GEN-LAST:event_laporanMNActionPerformed

    private void logoutMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMNActionPerformed
    this.dispose();
    FormLogin fLogIn= new FormLogin();
    fLogIn.setLocationRelativeTo(null);
    fLogIn.setVisible(true);
    }//GEN-LAST:event_logoutMNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenu MNreport;
    private javax.swing.JMenuItem barangMN;
    private javax.swing.JMenuItem laporanMN;
    private javax.swing.JMenu logoutMN;
    private javax.swing.JMenu masterMN;
    private javax.swing.JMenuItem penjuallanMN;
    private javax.swing.JMenu transactionMN;
    private javax.swing.JMenuItem userMN;
    // End of variables declaration//GEN-END:variables
}
